### ISSUE TITLE
How to change text color ? 

### ISSUE THREAD

**Issue by Phongvngg1** [Mortyick/enmity-themes#3]
I just want to change the color to black <because my background image is mixed black and white>

**Comment by Mortyick** [comment]
Text as in the text in a dm or channel?

“TEXT_NORMAL” is where you change that

Top one is for dark mode, bottom one is for light mode, just replace it with another hex color like #000000 (black) or #ffffff (white) or whatever other color like those

**Comment by Phongvngg1** [comment]
![image](https://github.com/Mortyick/enmity-themes/assets/87188286/2bb1ec64-e594-44e3-ac97-70500ce64df8)
Done, thank you
