### ISSUE TITLE
Install with caution

### ISSUE THREAD

**Issue by Rafbel04** [Mortyick/enmity-themes#4]
Trying to install StarNight absolutely nuked my install of Enmity. It no longer opens.

**Comment by Mortyick** [comment]
What version of Enmity (or Rosiecord) are you using?

**Comment by Rafbel04** [comment]
Under runtime versions, it says 294bf51 next to Enmity. It also says 2.2.6
next to tweak. Is that what you mean?

**Comment by Mortyick** [comment]
I meant the version of discord but ig the tweak info also helps

**Comment by Rafbel04** [comment]
Ah. Discord version 207.0

**Comment by Mortyick** [comment]
turns out i made a mistake in the url mb
also tested the theme with the tweak and version 208 and it works

**Comment by Rafbel04** [comment]
I see. How did you get a later version of discord? I installed the latest
version of enmity from GitHub and it came with this version.

**Comment by Mortyick** [comment]
i downloaded enmity from the app store and the tweak on my (old) jailbroken phone i had and tested the theme
